service: customersapi
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource:
        - "*"
functions:
  GetCustomers:
    handler: handler.getCustomers
    events:
      - http:
        path: /
        method: get
        cors: true
    vpc:
      securityGroupIds:
        - sg-ace7a8a3
      subnetIds:
        - subnet-a894f0ce
        - subnet-c29baf8f
        - subnet-86cf64b7
        - subnet-57cbaa08
        - subnet-43dd834d
        - subnet-091c7e28