service: register-patients

frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:PutItem
      - dynamodb:DeleteItem
      - dynamodb:GetItem
      - dynamodb:UpdateItem
    Resource: table-resource

functions:
  listPatients:
    handler: handler.listPatients
    events:
      - http:
          path: patients
          method: get

  showPatient:
    handler: handler.showPatient
    events:
      - http:
          path: patients/{patientId}
          method: get

  createPatient:
    handler: handler.createPatient
    events:
      - http:
          path: patients
          method: post

  updatePatient:
    handler: handler.updatePatient
    events:
      - http:
          path: patients/{patientId}
          method: put
  
  deletePatient:
    handler: handler.deletePatient
    events:
      - http:
          path: patients/{patientId}
          method: delete

resources:
  Resources:
    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PATIENTS
        AttributeDefinitions:
          - AttributeName: patient_id
            AttributeType: S
        KeySchema:
          - AttributeName: patient_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1